#!/bin/bash

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(integration|release|master)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]; then
    echo "You may not push to a protected branch. Please create a pull request."
    exit 1 # push will not execute
else
    exit 0 # push will execute
fi
